[package]
name = "autopulse-crm/frontend"
version = "0.1.0"
description = "AutoPulse CRM â€“ HSR Motors Frontend"

[[module]]
name = "static-web-server"
source = "wasmer.io/wasmer/static-web-server@^1"

[fs]
"/public" = "dist"

[[command]]
name = "server"
module = "static-web-server"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/public", "-p", "8080"]
